version: "3.9"

services:
  nb:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - .:/usr/src/workspace
    working_dir: /usr/src/workspace/
    # largely unsafe if performed on a remote server
    # https://stackoverflow.com/questions/41159797/how-to-disable-password-request-for-a-jupyter-notebook-session#47509274
    entrypoint: ["jupyter","lab","--ip='*'","--port=8888", "--no-browser", "--allow-root", "--NotebookApp.token=''"]
